### PR TITLE
sub-module layout

### PR DESCRIPTION
**Pull request by JalonSolov**
Here's what I was talking about for doing submodules.  Seems to work fine, for me.

May not be quite right to use as a separate module, take a look.

### CODE REVIEW

**Comment by Sorrow446** [comment]
Thank you. How would this work through vpm install now? Am still considering whether or not to keep the formats separate.

**Comment by JalonSolov** [comment]
You'll have to rename the repo to `vtag` instead of `v-tag`, but once you do...

First, install with `v install Sorrow446/vtag` then...
```v
import vtag.flac
import vtag.id3
import vtag.mp4

fn main() {
        flac_tags := flac.read('1.flac') or {
                panic(err)
        }
        println(flac_tags.album)

        mp4_tags := mp4.read('1.m4a') or { panic(err) }
        println(mp4_tags.album)

        id3_tags := id3.read('1.mp3') or { panic(err) }

        println(id3_tags.album)
}
```

**Comment by JalonSolov** [comment]
You can test this locally by making a link from `.vmodules/vtag` to your local clone.

**Comment by Sorrow446** [comment]
That's great then, thanks. I'll have another look soon. Wanna implement an "open" system I did here: https://github.com/Sorrow446/v-flactag.

**Comment by JalonSolov** [comment]
That looks good, too.  Then you only install the one for the format you need, instead of one that handles everything.

Just FYI - V won't install it as a module with the `-` in the name.

**Pull request merged**
